name: Release
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          uv build
          uv publish --token $PYPI_TOKEN
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install JS dependencies
        run: bun install
      - name: Publish to npm
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_API_TOKEN }}
        run: bun publish --access public
