name: pytest

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "14 3 * * 1" # at 03:14 on Monday.

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
        os:
          - ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      znsocket:
        image: pythonf/znsocket
        options: >-
          --health-cmd "python healthcheck.py"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 4748:4748

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install python packages
        run: uv sync --all-extras --dev
      - name: Install javascript packages
        run: |
          npm install
      - name: Run pytest
        continue-on-error: true
        run: |
          uv run python --version
          uv run coverage run -m pytest
          uv run coverage lcov
      - name: Run jest
        run: |
          bun test --test-name-pattern native_
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
